---
title: "lab 4"
author: "Kordell Schrock"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(hash)
library(dplyr)
library(ggplot2)
library(devtools)
library(data.table)
library(anytime)
library(data.table)
library(knitr)
library(tidyr)
library(reshape2)
```

```{r}
library(readxl)
defense <- read_excel('./cyclonesFootball2019.xlsx', sheet='Defensive')
offense <- read_excel('./cyclonesFootball2019.xlsx', sheet='Offensive')
biography <- read_excel('./cyclonesFootball2019.xlsx', sheet='Biography')
str(defense)
```
## Part 1: Cleaning data
```{r}

offenseClean <- offense %>%
  mutate(Name = factor(Name),
         Opponent_Opponent = factor(Opponent_Opponent)) %>%
  mutate(across(Rushing_ATT:Passing_INT, as.numeric))
    #cleaning the offense

defenseClean <- defense %>%
  mutate(Name = factor(Name),
         Opponent_Opponent=factor(Opponent_Opponent)) %>%
  mutate(across(Tackles_Solo:Pass_PB, as.numeric))
  #cleaning the defense

biographyClean <- biography %>%
  mutate(Weight = as.numeric(Weight)) %>%
  separate(Height, c("feet","inches"), "-") %>%
  mutate(Height = as.numeric(feet)* 12 + as.numeric(inches)) %>%
  select(-feet, -inches)
  #cleaning the biography

str(defenseClean) #print dataset
str(offenseClean) #print dataset
str(biographyClean) #print dataset

```
## Part 2: Tidying
#Reformat the defClean data frame into a tidy format using pivot_longer. The type of statistic (Tackles_Solo, Tackles_ASST, etc) is added as a new key column named stat.
```{r}
#1
defenseClean<-defenseClean %>%
  pivot_longer(Tackles_Solo:Pass_PB, names_to = 'stat')
```
##Compare the distributions of the defensive statistics. What defensive skills are rare?

```{r}
#2
sumOfStats <- defenseClean %>% 
  group_by(stat) %>% #group by statistics
  summarise(sum = sum(value)) %>% #get the sum
  arrange(sum)

print(sumOfStats) #print the dataset

ggplot(defenseClean, aes(x=value)) + geom_histogram(bins=10) + facet_wrap(~stat) + ggtitle('Histograms of Defensive Stats bins=10') + xlab('Value of Defensive Stats') + ylab('Count of Defensive Stats')
#create histogram of Defensive Stats

ggplot(defenseClean, aes(x = reorder(stat, value), y = value)) + geom_bar(stat = 'identity') + coord_flip() + labs(x = 'Stat', y = 'Frequency', title = 'Defensive Stats Freq')
#create bar chart of Defensive Stats
```

```{r}
#3
iowaVSnotreDame <- defenseClean %>%
  group_by(Opponent_Opponent) %>% #group by teams
  filter( Opponent_Opponent == "Notre Dame" | Opponent_Opponent == "Iowa" ) %>% #filters by Iowa or Notre Dame
  filter(stat == "Tackles_Solo") %>% #filter by Solo Tackles
  rename(teams = Opponent_Opponent) #rename column

str(iowaVSnotreDame) #display dataframe

  
ggplot(iowaVSnotreDame, aes(x = value, y = Name)) + facet_wrap(iowaVSnotreDame$teams) + geom_point() + ggtitle('Solo Tackles for the Iowa and Notre Dame Game') + xlab('Number of Solo Tackles') + ylab(' Football Players') 
#Create scater plot of Iowa and Notre Dame Players for Solo Tackles for each player.
# Use facet_wrap() to to show teams variables: Iowa and Notre Dame
```

```{r}
#4
biographyClean <- biographyClean %>%
  separate(Hometown, c('City', 'State'), sep =", ") #create 2 columns City and State from Hometown.
str(biographyClean) #print clean biography dataset
```

```{r}
#5
playersPerState <- biographyClean %>%
      group_by(State) %>% #group by state
      summarize(count = n()) %>% #tally
      distinct(State, count) %>% #get distinct values
      arrange(count, State) #arrange state by count

print(playersPerState) #print dataset
```

